- name: Install Puppet repo
  yum:
    name: https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
    state: present

- name: Install Foreman repo
  yum:
    name: https://yum.theforeman.org/releases/2.1/el7/x86_64/foreman-release.rpm
    state: present

- name: Install Katello repo
  yum:
    name: https://fedorapeople.org/groups/katello/releases/yum/3.16/katello/el7/x86_64/katello-repos-latest.rpm
    state: present

- name: Install foreman-release-scl
  yum:
    name: foreman-release-scl
    state: latest

- name: Install katello package
  yum:
    name: katello
    state: latest
    
- name: Firewall - Opening Ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - 5646/tcp
    - 5647/tcp
    - 8000/tcp
    - 8140/tcp
    - 9090/tcp
    - 69/udp
    - 5000/tcp
    - 5900-5930/tcp

- name: Adding to hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}  {{ ansible_hostname }}'

- name: Install Foreman Application
  command: >
    foreman-installer --scenario katello

- name: Get admin password
  shell: "grep 'foreman::params::initial_admin_password' /var/log/foreman-installer/katello.log | awk -F ' ' '{print $(NF)}'| awk 'END{print}'"
  register: initial_admin_password

- debug:
    msg:
    - "The address to manage Foreman is: https://{{ ansible_fqdn }}"
    - "Initial credentials are admin / {{ initial_admin_password.stdout }}"