- name: Install pre-requisites
  yum:
    name: "{{ pre_gitlab_pkgs }}"
    state: present
  vars:
    pre_gitlab_pkgs:
    - postfix
    - curl
    - policycoreutils-python

- name: Install Gitlab repo
  shell: " curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash"
  args:
    warn: no
    
- name: Firewall - Opening Ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- name: Install Gitlab
  yum:
    name: gitlab-ce
    state: latest
  environment:
    EXTERNAL_URL: http://{{ ansible_fqdn }}
