- name: install MySQL 8 Repo
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm  
    state: present

- name: Install MySQL 8
  yum:
    name: mysql-community-server
    state: present

- name: Install python for Ansible/MySQL
  yum:
    name: "{{ mysql_pkgs }}"
    state: present
  vars:
    mysql_pkgs:
    - python2-PyMySQL
    - MySQL-python

- name: Enable Native Password in my.cnf file
  lineinfile:
    path: /etc/my.cnf
    regexp: '^# default-authentication-plugin='
    line: default-authentication-plugin=mysql_native_password

- name: Start Service MySQL
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: root_password

- name: Update Autogenerate root password
  command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"

- name: Remove test Database
  mysql_db:    
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent

- name: Remove Anonymous users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ""
    host_all: yes
    state: absent
